/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab12;

/**
 *
 * @author Lenovo
 */

import javax.swing.JOptionPane;
enum ComboTextValues {
    comboText, comboText1, comboText2;
}

enum ButtonValues {
    button, button1, button2
}

enum LabelValues {
    label, label1, label2
}
public class MyComponent extends javax.swing.JPanel {

    /**
     * Creates new form myComponent
     */
    public MyComponent() {
        initComponents();
        String[] lines = {"1.", "2.","3.","4."};
        setComboBoxText(lines);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */                      
                              

     private void showInfo(String pressed) {
        JOptionPane.showMessageDialog(this, "Selected items index = " + jComboBox1.getSelectedIndex() + "\n" + pressed + " pressed");
        jButton1.setVisible(true);
    }
     
     public void setComboBoxText(String[] lines) {
        jComboBox1.removeAllItems();
        for (String line : lines) {
            jComboBox1.addItem(line);
        }
    }
    LabelValues labels;

    public void setjLabel(LabelValues labels) {
        this.labels = labels;
        switch (labels) {
            case label:
                jLabel1.setText("First label");
                break;
            case label1:
                jLabel1.setText("Second label");
                break;
            case label2:
                jLabel1.setText("Third label");
                break;

        }
    }

    public LabelValues getjLabel() {
        return labels;
    }

    ButtonValues buttons;

    public void setjButton(ButtonValues buttons) {
        this.buttons = buttons;
        switch (buttons) {
            case button:
                jButton1.setText("First button");
                break;
            case button1:
                jButton1.setText("Second button");
                break;
            case button2:
                jButton1.setText("Third button");
                break;
        }
    }

    public ButtonValues getjButton() {
        return buttons;
    }

    ComboTextValues comboBoxes;

    public void setjComboBox(ComboTextValues comboBox) {
        this.comboBoxes = comboBox;
        switch (comboBoxes) {
            case comboText:
                setComboBoxText(new String[]{"1)", "2)", "3)","4)"});
                break;
            case comboText1:
                setComboBoxText(new String[]{"a)", "b)", "c)", "d)"});
                break;
            case comboText2:
                setComboBoxText(new String[]{"I", "II", "III", "IV"});
                break;
        }
    }

    public ComboTextValues getjComboBox() {
        return comboBoxes;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(116, 116, 116))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showInfo("Button");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
